### ISSUE TITLE
10.	Reading stories-APP

### ISSUE THREAD

**Issue by Curstan** [fidhub/infoshare#75]
**Precondition:**
 the user has logged into the system 

**User story:**
  As a user I want to be able to view comments made on published stories.

 **Post condition:** 
 the user can now read all the comments made by other users.

**Comment by Mikhail17** [comment]
As a user, I want to read article written within my organization so that I learn about others expertise 

Precondition:
- User logs on the InfoShare server by using the App
-  User is navigated to the home page where many different articles are written 
- User clicks on an article
- Article opens up for the user to read

Post-condition:
- User is able to read articles written

**Comment by zeentle** [comment]
As a user, I want to read articles published within my organization so that I can get information 

Precondition: -user logs into the InfoShare app
                     -user navigates through the app to find the different articles
                     - user clicks on the article that he/she wants read
                     - article opens up

Post-condition: user reads the article

**Comment by smkumatela** [comment]
Guys please flag Dr Kabaso that there is no API for comments yet so even if i do the UI for comments, there is still no API for saving those comments because we can already read published articles
